```{r}
library(hoopR)
library(tidyverse)
```

```{r}
feb8games <- load_nba_schedule(seasons = most_recent_nba_season()) %>% 
  filter(grepl("2024-02-09", date))
```




```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 1000000)
nba_teams <- nba_leaguestandings(league_id = '00', season = year_to_season(most_recent_nba_season() - 1))$Standings
feb8home_teams <- feb8games %>% 
  merge(nba_teams, by.x = "home_short_display_name", by.y = "TeamName")
feb8away_teams <- feb8games %>% 
  merge(nba_teams, by.x = "home_short_display_name", by.y = "TeamName")
feb8teams <- rbind(feb8home_teams, feb8away_teams)$TeamID

```

```{r}
feb8players <- nba_commonteamroster(season = year_to_season(most_recent_nba_season() - 1), 
                     team_id = feb8teams[1])$CommonTeamRoster
for (team in feb8teams[-1]) {
  feb8players <- rbind(feb8players,
                       nba_commonteamroster(season = year_to_season(most_recent_nba_season() - 1), 
                     team_id = team)$CommonTeamRoster)
}
```


```{r}
nba_playergamelog(player_id = '2544')
```
```{r}
library(hoopR)
freddys_funtime <- function(player_name, stat, over_under, odds, risk = 1) {
  
}
```

```{r}
player_id <- nba_commonallplayers(league_id = '00', 
                     season = year_to_season(most_recent_nba_season() - 1))$CommonAllPlayers %>% 
  as.data.frame() %>% 
  filter(DISPLAY_FIRST_LAST == "Jayson Tatum")

player_id <- player_id$PERSON_ID

player_summaries <- nba_playergamelog(player_id = player_id)$PlayerGameLog %>% 
  filter(MATCHUP == "BOS @ BKN" | MATCHUP == "BOS vs. BKN")

player_summaries <- player_summaries %>% 
  mutate(stat = as.numeric(player_summaries[["REB"]])) %>% 
  summarize(mean_stat = mean(stat),
            sd_stat = sd(stat))



pnorm(8.5, mean = player_summaries$mean_stat, 
      sd = player_summaries$sd_stat)
```
```{r}
 nba_leagueplayerondetails(team_id = '1610612749', season = year_to_season(most_recent_nba_season() - 1))
```

```{r}

```


